apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
stringData:
  host: __db_host__
  username: __db_username__
  password: __db_password__
#can be used with replace token in azure devops pipeline and replace with pipeline variables
